variables:
  IMAGE_TAG: honza801/kubackup:v0.2

stages:
  - buildapp
  - buildimage

build kubackup:
  stage: buildapp
  image: golang:1.19
  script:
    - go mod init kubackup
    - go mod tidy
    - CGO_ENABLED=0 go build .
  artifacts:
    paths:
      - kubackup

build docker image:
  stage: buildimage
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  dependencies:
    - build kubackup
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${IMAGE_TAG}"
