stages:
  - buildapp
  - buildimage

build kubackup:
  stage: buildapp
  image: golang:latest
  script:
    - go build .
  artifacts:
    paths:
      - kubackup

build docker image:
  stage: buildimage
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  dependencies:
    - build kubackup
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
