apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubackup
spec:
  schedule: "2 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubackup
            image: honza801/kubackup:v0.2
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: kubackup-env
            volumeMounts:
            - name: kubackup-config
              mountPath: /etc/kubackup
          restartPolicy: OnFailure
          serviceAccountName: kubackup
          volumes:
          - name: kubackup-config
            configMap:
              name: kubackup-config
