apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubackup-system

resources:
- namespace.yaml
- rbac.yaml
- cronjob.yaml

configMapGenerator:
- name: kubackup-config
  files:
  - config.yaml

secretGenerator:
- name: kubackup-env
  envs:
  - env
