apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubackup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubackup
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - pods/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/attach
  - pods/exec
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubackup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubackup
subjects:
- kind: ServiceAccount
  name: kubackup
  namespace: default
